"""empty message

Revision ID: 271d4518e582
Revises: 967e6be1f5a3
Create Date: 2018-09-03 21:38:09.407796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271d4518e582'
down_revision = '967e6be1f5a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wushu_users', sa.Column('email_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wushu_users', 'email_confirmed')
    # ### end Alembic commands ###
