"""empty message

Revision ID: 3cd9e9b6f3f1
Revises: 
Create Date: 2018-08-30 22:46:07.533928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd9e9b6f3f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wushu_provinces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('countryid', sa.Integer(), nullable=False),
    sa.Column('canDelete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wushu_teams',
    sa.Column('id', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.String(length=20), nullable=False),
    sa.Column('owner_name', sa.String(length=20), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wushu_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.Column('login_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('wushu_cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('provinceid', sa.Integer(), nullable=True),
    sa.Column('canDelete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['provinceid'], ['wushu_provinces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wushu_districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('cityid', sa.Integer(), nullable=True),
    sa.Column('canDelete', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cityid'], ['wushu_cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wushu_districts')
    op.drop_table('wushu_cities')
    op.drop_table('wushu_users')
    op.drop_table('wushu_teams')
    op.drop_table('wushu_provinces')
    # ### end Alembic commands ###
