"""empty message

Revision ID: 967e6be1f5a3
Revises: 897066fb86bb
Create Date: 2018-08-31 22:24:36.766281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '967e6be1f5a3'
down_revision = '897066fb86bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wushu_teams', sa.Column('cityid', sa.String(length=20), nullable=False))
    op.add_column('wushu_teams', sa.Column('countryid', sa.String(length=20), nullable=False))
    op.add_column('wushu_teams', sa.Column('provinceid', sa.String(length=20), nullable=False))
    op.drop_column('wushu_teams', 'province')
    op.drop_column('wushu_teams', 'city')
    op.drop_column('wushu_teams', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wushu_teams', sa.Column('country', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=False))
    op.add_column('wushu_teams', sa.Column('city', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=False))
    op.add_column('wushu_teams', sa.Column('province', mysql.VARCHAR(collation='utf8_bin', length=20), nullable=False))
    op.drop_column('wushu_teams', 'provinceid')
    op.drop_column('wushu_teams', 'countryid')
    op.drop_column('wushu_teams', 'cityid')
    # ### end Alembic commands ###
